version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: specterhub
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  specterhub:
    image: ghcr.io/aleshorvat/specterhub:latest
    pull_policy: never
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      DATABASE_PATH: /app/data/specterhub.db
      JWT_SECRET: ${APP_SEED}
      SSH_PASSWORD_ENCRYPTION_KEY: ${APP_SSH_PASSWORD_ENCRYPTION_KEY}
      ADMIN_USERNAME: ${APP_ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${APP_PASSWORD}
